### PR TITLE
Fix markdown for numbered list

### PR DESCRIPTION
**Pull request by jeffreyzupka**
Add a new line above the numbered list.

### CODE REVIEW

**Comment by jeffreyzupka** [comment]
@greenkiwi?

**Comment by sujanturo** [comment]
👍

**Comment by greenkiwi** [comment]
Thanks Jeff

**Comment by tobyoconnell** [comment]
Public service announcement: For numbered lists, you can, and probably should, use the number one for each item and let the markdown generator count.

This markdown
```
1. first
1. second
1. third
```
generates the following text

1. first
1. second
1. third

**Pull request merged**
